acg.pcg.combined <- read.csv(file.choose(), header=TRUE)
na.exclude(acg.pcg.combined)
GSH.model = lmer(GSH ~ Region + Time + GSH..SD + (1|Subject), data=acg.pcg.combined)
summary(GSH.model)
residuals.gsh <- resid(GSH.model)
plot(GSH.model, xlab = "Concentration", ylab = "GSH Residual")
Ins.model = lmer(Ins ~ Time + Region + Ins..SD + (1|Subject), data=acg.pcg.combined)
summary(Ins.model)
residuals.ins <- resid(Ins.model)
plot(Ins.model, xlab = "Concentration", ylab = "Ins Residual")
NAA.NAAG.model = lmer(NAA.NAAG ~ Time + Region + NAA.NAAG..SD + (1|Subject), data=acg.pcg.combined)
summary(NAA.NAAG.model)
residuals.naa.naag <- resid(NAA.NAAG.model)
plot(NAA.NAAG.model, xlab = "Concentration", ylab = "NAA + NAAG Residual")
GABA.model = lmer(GABA ~ Time + Region + GABA..SD + (1|Subject), data=acg.pcg.combined)
summary(GABA.model)
residuals.gaba <- resid(GABA.model)
plot(GABA.model, xlab = "Concentration", ylab = "GABA Residual")
GPC.PCh.model = lmer(GPC.PCh ~ Time + Region + GPC.PCh..SD + (1|Subject), data=acg.pcg.combined)
summary(GPC.PCh.model)
residuals.gpc.pch <- resid(GPC.PCh.model)
plot(GPC.PCh.model, xlab = "Concentration", ylab = "GPC + PCh Residual")
Cr.PCr.model = lmer(Cr.PCr ~ Time + Region + Cr.PCr..SD + (1|Subject), data=acg.pcg.combined)
summary(Cr.PCr.model)
Glu.Gln.model = lmer(Glu.Gln ~ Time + Region + Glu.Gln..SD + (1|Subject), data=acg.pcg.combined)
summary(Glu.Gln.model)
residuals.glu.gln <- resid(Glu.Gln.model)
plot(Glu.Gln.model, xlab = "Concentration", ylab = "Glu + Gln Residual")
Asp.model = lmer(Asp ~ Time + Region + Asp..SD + (1|Subject), data=acg.pcg.combined)
summary(Asp.model)
residuals.asp <- resid(Asp.model)
plot(Asp.model, xlab = "Concentration", ylab = "Asp Residual")

