acg.pcg.combined <- read.csv(file.choose(), header=TRUE)
acg.pcg.combined
GSH.model = lmer(GSH ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(GSH.model)
residuals.gsh <- resid(GSH.model)
summary(residuals.gsh)
hist(residuals.gsh)
Ins.model = lmer(Ins ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(Ins.model)
residuals.ins <- resid(Ins.model)
summary(residuals.ins)
hist(residuals.ins)
NAA.NAAG.model = lmer(NAA.NAAG ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(NAA.NAAG.model)
residuals.naa.naag <- resid(NAA.NAAG.model)
summary(residuals.naa.naag)
hist(residuals.naa.naag)
GABA.model = lmer(GABA ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(GABA.model)
residuals.gaba <- resid(GABA.model)
summary(residuals.gaba)
hist(residuals.gaba)
GPC.PCh.model = lmer(GPC.PCh ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(GPC.PCh.model)
residuals.gpc.pch <- resid(GPC.PCh.model)
summary(residuals.gpc.pch)
hist(residuals.gpc.pch)
Cr.PCr.model = lmer(Cr.PCr ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(Cr.PCr.model)
Glu.Gln.model = lmer(Glu.Gln ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(Glu.Gln.model)
residuals.glu.gln <- resid(Glu.Gln.model)
summary(residuals.glu.gln)
hist(residuals.glu.gln)
Asp.model = lmer(Asp ~ Time + Region + (1|Subject), data=acg.pcg.combined)
summary(Asp.model)
residuals.asp <- resid(Asp.model)
summary(residuals.asp)
hist(residuals.asp)
